spring:
  datasource:
    username: root
    password: 12102005
    url: jdbc:mysql://localhost:3306/anihoyo
  jpa:
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  data:
    redis:
      host: localhost
      port: 6377
openapi:
  service:
    api-docs: api-service
    serverUrl: http://localhost:${server.port}
    serverName: Server Dev
    title: API Document
    version: 1.0.0

anihoyo:
  jwt:
    base64-secret: qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==

hieupham:
  upload-file:
    base-uri: file:///D:/Side-project/AniHoyo-RestfulService/storage/
  ffmpeg-path: C:\ffmpeg\bin\ffmpeg.exe
