spring:
  datasource:
    username: root
    password: 12102005
    url: jdbc:mysql://localhost:3306/anihoyo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: format_sql:true
  application:
    name: AniHoyo
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
anihoyo:
  jwt:
    base64-secret: qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
    access-token-validity-in-seconds: 8640
    refresh-token-validity-in-seconds: 864000
server:
  port: 8083
files:
  video: videos/
#config upload file
hieupham:
  upload-file:
    base-uri: file:///D:/WhatWeDone-Will/AniHoyo-ReactSpring-restfulService/storage/
